name: run test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clean
      run: |
       pushd build
       bash clean.sh
       popd
    - name: make
      run: |
        pushd build
        bash make.sh
        popd